import assert from "node:assert/strict";
import * as fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { mock, test } from "node:test";
import { DeviceRouter } from "../src/device-router.js";
import { FakeVoiceHost, MockedVoiceWorkerClient, assistant } from "./helpers/fake-voice-host.js";

mock.module("../src/worker-client.js", { namedExports: { VoiceWorkerClient: MockedVoiceWorkerClient } });
const pickerUI = await import("../src/device-picker-ui.js");
// This suite checks routing transactions; mounted native overlay/lifecycle coverage lives separately.
mock.module("../src/device-picker-ui.js", { namedExports: { ...pickerUI,
	selectDeviceOverlay: (ctx: any, labels: string[], signal: AbortSignal) => ctx.ui.select("Voice device", labels, { signal }),
} });
const settle = async () => { for (let i = 0; i < 30; i++) await new Promise(resolve => setImmediate(resolve)); };

test("picker snapshots unique labels, cancels read-only, revalidates and uses the safe sticky transition", async t => {
	const root = await fs.mkdtemp(path.join(os.tmpdir(), "voice-picker-"));
	const keys = ["PI_VOICE_CONFIG", "PI_VOICE_COORDINATOR_DIR", "PI_VOICE_DEVICE_DIR"];
	const old = keys.map(key => process.env[key]);
	process.env.PI_VOICE_CONFIG = path.join(root, "config.json");
	process.env.PI_VOICE_COORDINATOR_DIR = path.join(root, "coordinator");
	process.env.PI_VOICE_DEVICE_DIR = path.join(root, "devices");
	await fs.mkdir(process.env.PI_VOICE_DEVICE_DIR);
	await fs.writeFile(process.env.PI_VOICE_CONFIG, JSON.stringify({ enabled: true, input: "disabled", audioCache: false, timingPreprocessConcurrency: 0 }));
	const ids = ["same-prefix-123-A", "same-prefix-123-B"];
	const register = async (id: string, name = "手机 [same]") => {
		await fs.writeFile(path.join(root, id), "");
		await fs.writeFile(path.join(process.env.PI_VOICE_DEVICE_DIR!, `${id}.json`), JSON.stringify({ version: 1, id, name, platform: "linux",
			audioEndpoint: `unix://${root}/${id}`, inputEndpoint: `unix://${root}/${id}`, connectedAt: 1, lastActive: 1 }));
	};
	await Promise.all(ids.map(id => register(id)));
	await register("bad", "bad\x1b[31m");
	t.mock.method(DeviceRouter.prototype, "resolveCurrentConnection", async () => ({ kind: "device" as const, id: ids[0] }));
	const host = new FakeVoiceHost(root, "picker");
	let editor = "Keep my draft";
	host.ctx.ui.getEditorText = () => editor;
	host.ctx.ui.setEditorText = (value: string) => { editor = value; };
	let options: string[] = [];
	let answer = Promise.withResolvers<string | undefined>();
	host.ctx.ui.select = (_title: string, labels: string[]) => { options = labels; return answer.promise; };
	t.after(async () => {
		await host.shutdown();
		keys.forEach((key, i) => { if (old[i] === undefined) delete process.env[key]; else process.env[key] = old[i]; });
		await fs.rm(root, { recursive: true, force: true });
	});
	await host.start();
	host.addMessage("answer", null, assistant("First sentence. Second sentence."));
	await host.shortcut("f5"); await settle();
	const worker = MockedVoiceWorkerClient.instances.at(-1)!;
	const pins = () => host.entries.filter(entry => entry.customType === "pi-voice.device-selection");
	const before = { pins: pins().length, pauses: worker.pauses.length, sent: worker.sent.length };
	host.scrollView.setDocument(Array.from({ length: 100 }, (_, i) => `${i}`));
	host.scrollView.manualScrollTo(20);
	let opening = host.shortcut("alt+d");
	assert.equal(options.length, 3, "only local and valid available registrations");
	assert.equal(new Set(options).size, 3, "duplicate names and short-ID prefixes remain distinct");
	assert.match(options[1], /current/);
	assert.equal(pins().length, before.pins);
	assert.equal(worker.pauses.length, before.pauses);
	assert.equal(worker.sent.length, before.sent);
	answer.resolve(undefined); await opening;
	assert.equal(host.scrollView.scrollTop, 20);
	assert.equal(editor, "Keep my draft");
	assert.equal(worker.pauses.length, before.pauses);
	answer = Promise.withResolvers(); opening = host.command("devices");
	await fs.rm(path.join(root, ids[1]));
	answer.resolve(options[2]); await opening;
	assert.equal(pins().length, before.pins, "expired endpoint cannot commit");
	assert.equal(worker.pauses.length, before.pauses, "expiration before choose is read-only");
	await register(ids[1]);
	answer = Promise.withResolvers(); opening = host.shortcut("alt+d");
	await host.command("device local");
	answer.resolve(options[2]); await opening;
	assert.equal(pins().at(-1).data.pin, "local", "newer explicit control supersedes the picker");
	answer = Promise.withResolvers(); opening = host.shortcut("alt+d");
	const stop = Promise.withResolvers<void>();
	const terminate = t.mock.method(worker, "terminate", () => stop.promise);
	answer.resolve(options[2]); await settle();
	assert.equal(pins().at(-1).data.pin, "local", "selection awaits actual stop proof");
	stop.resolve(); await opening;
	terminate.mock.restore();
	assert.equal(pins().at(-1).data.pin, ids[1]);
	assert.equal(pins().at(-1).data.selection, ids[1]);
	assert.equal(editor, "Keep my draft");
	assert.equal(host.scrollView.scrollTop, 20);
	assert.equal(worker.sent.length, before.sent, "choosing stays silent");
	assert.match(host.widgetComponents.get("pi-voice-progress")!.render!(80)[0], /Paused/);
	// A registration can expire while the old player is stopping, not just while choosing.
	answer = Promise.withResolvers(); opening = host.shortcut("alt+d");
	const delayedStop = Promise.withResolvers<void>();
	const delayed = t.mock.method(worker, "terminate", () => delayedStop.promise);
	answer.resolve(options[1]); await settle();
	await fs.rm(path.join(root, ids[0]));
	delayedStop.resolve(); await opening; delayed.mock.restore();
	assert.equal(pins().at(-1).data.pin, ids[1], "post-stop revalidation rejects expired endpoints");
	await register(ids[0]);
	answer = Promise.withResolvers(); opening = host.shortcut("alt+d");
	const failed = t.mock.method(worker, "terminate", async () => { throw new Error("stop unconfirmed"); });
	answer.resolve(options[1]); await opening; failed.mock.restore();
	assert.equal(pins().at(-1).data.pin, ids[1], "failed stop cannot commit picker choice");
	await host.command(`device ${ids[1]}`);
	answer = Promise.withResolvers(); opening = host.shortcut("alt+d");
	const sessionId = host.sessionManager.getSessionId;
	host.sessionManager.getSessionId = () => "replacement";
	answer.resolve(options[0]); await opening;
	assert.equal(pins().at(-1).data.pin, ids[1], "dynamic session replacement fences an old choice");
	host.sessionManager.getSessionId = sessionId;
	answer = Promise.withResolvers(); opening = host.shortcut("alt+d");
	const count = pins().length;
	await host.shutdown();
	answer.resolve(options[0]); await opening;
	assert.equal(pins().length, count, "shutdown fences delayed selection");
});
