/** Default effective query values; transport fixtures may override input/output. */
export const voiceQueryCases: ReadonlyArray<readonly [string, RegExp]> = [
	["mode", /^mode: assistant$/],
	["voice", /^voice: af_heart$/],
	["speed", /^speed: 1$/],
	["tts-model", /^tts-model: onnx-community\/Kokoro-82M-v1.0-ONNX$/],
	["tts-dtype", /^tts-dtype: q8$/],
	["tts-workers", /^tts-workers concurrency: [1-8]$/],
	["tts-worker", /^tts-workers concurrency: [1-8]$/],
	["stt-model", /^stt-model: onnx-community\/whisper-tiny.en$/],
	["stt-dtype", /^stt-dtype: fp32$/],
	["stt-candidates", /^stt-candidates: 3$/],
	["alignment-model", /^alignment-model: onnx-community\/wav2vec2-base-960h-ONNX$/],
	["alignment-dtype", /^alignment-dtype: q8$/],
	["edit-model", /^edit-model: current → test\/model$/],
	["highlight", /^highlight: on$/],
	["autoscroll", /^autoscroll: on$/],
	["code-narration", /^code-narration: guided$/],
	["code-preprocess", /^code-preprocess: 4$/],
	["code-budget", /scope=since-compaction; budget=25; used=0;/],
	["timing", /^Word timing: [^\n]+\n.+\nTiming workers: auto → [1-4](; active batch=\d+)?$/],
	["timing workers", /^timing workers: auto → [1-4]$/],
	["audio-cache", /^audio-cache: off$/],
	["audio-bitrate", /^audio-bitrate: 32 kbps$/],
	["device", /^device: auto → local$/],
	["output", /^output: local \(explicit\)$/],
	["input", /^input: disabled \(explicit\)$/],
	["shortcut", /^shortcut: alt\+m \(also f4\)$/],
	["submit", /^submit: review$/],
	["edit", /^edit: smart$/],
];
